import { User, StudentProfile, Internship, Company, Application, University } from '../types';

export const MOCK_UNIVERSITIES: University[] = [
  { id: 'u1', name: 'University of Zambia (UNZA)', location: 'Lusaka' },
  { id: 'u2', name: 'Copperbelt University (CBU)', location: 'Kitwe' },
  { id: 'u3', name: 'Mulungushi University', location: 'Kabwe' },
];

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'ZICTA',
    description: 'Zambia Information and Communications Technology Authority (ZICTA) is the regulator for the ICT sector in Zambia.',
    logo: 'https://picsum.photos/seed/zicta/200/200',
    website: 'https://www.zicta.zm',
    location: 'Lusaka',
  },
  {
    id: 'c2',
    name: 'Airtel Zambia',
    description: 'A leading telecommunications company in Zambia.',
    logo: 'https://picsum.photos/seed/airtel/200/200',
    website: 'https://www.airtel.co.zm',
    location: 'Lusaka',
  },
  {
    id: 'c3',
    name: 'Mopani Copper Mines',
    description: 'One of the largest mining companies in Zambia.',
    logo: 'https://picsum.photos/seed/mopani/200/200',
    website: 'https://www.mopani.com.zm',
    location: 'Kitwe',
  },
];

export const MOCK_INTERNSHIPS: Internship[] = [
  {
    id: 'i1',
    companyId: 'c1',
    companyName: 'ZICTA',
    companyLogo: 'https://picsum.photos/seed/zicta/200/200',
    title: 'Cybersecurity Intern',
    description: 'Join our cybersecurity team to help protect national digital infrastructure. You will assist in threat monitoring and incident response.',
    requirements: ['Computer Science or related degree', 'Basic knowledge of networking', 'Strong analytical skills'],
    location: 'Lusaka',
    category: 'Technology',
    deadline: '2026-06-30',
    postedAt: '2026-04-10',
    status: 'OPEN',
  },
  {
    id: 'i2',
    companyId: 'c2',
    companyName: 'Airtel Zambia',
    companyLogo: 'https://picsum.photos/seed/airtel/200/200',
    title: 'Network Operations Trainee',
    description: 'Support the core network team in maintaining nationwide connectivity. Hands-on experience with telecommunications equipment.',
    requirements: ['Telecommunications Engineering student', '3rd year or above', 'Proactive learner'],
    location: 'Lusaka',
    category: 'Engineering',
    deadline: '2026-05-15',
    postedAt: '2026-04-12',
    status: 'OPEN',
  },
  {
    id: 'i3',
    companyId: 'c3',
    companyName: 'Mopani Copper Mines',
    companyLogo: 'https://picsum.photos/seed/mopani/200/200',
    title: 'Mining Engineering Intern',
    description: 'Get real-world experience in deep-level mining operations. You will rotate through various departments in the Kitwe mine.',
    requirements: ['Mining Engineering degree in progress', 'Strong safety consciousness', 'Willing to work in Kitwe'],
    location: 'Kitwe',
    category: 'Mining',
    deadline: '2026-07-01',
    postedAt: '2026-04-05',
    status: 'OPEN',
  },
];

export const MOCK_USERS: (User | StudentProfile)[] = [
  {
    id: 's1',
    email: 'student@unza.zm',
    name: 'Bwalya Mulenga',
    role: 'STUDENT',
    universityId: 'u1',
    university: 'University of Zambia (UNZA)',
    course: 'Computer Science',
    yearOfStudy: 3,
    skills: ['React', 'JavaScript', 'Python'],
    savedInternshipIds: [],
  },
  {
    id: 's2',
    email: 'mutale@unza.zm',
    name: 'Mutale Chanda',
    role: 'STUDENT',
    universityId: 'u1',
    university: 'University of Zambia (UNZA)',
    course: 'Business Administration',
    yearOfStudy: 4,
    skills: ['Accounting', 'Sales'],
    savedInternshipIds: [],
  },
  {
    id: 's3',
    email: 'lombe@cbu.zm',
    name: 'Lombe Kabwe',
    role: 'STUDENT',
    universityId: 'u2',
    university: 'Copperbelt University (CBU)',
    course: 'Mining Engineering',
    yearOfStudy: 3,
    skills: ['Geology', 'Safety'],
    savedInternshipIds: [],
  },
  {
    id: 's4',
    email: 'mapalo@cbu.zm',
    name: 'Mapalo Phiri',
    role: 'STUDENT',
    universityId: 'u2',
    university: 'Copperbelt University (CBU)',
    course: 'Electrical Engineering',
    yearOfStudy: 2,
    skills: ['Circuits', 'CAD'],
    savedInternshipIds: [],
  },
  {
    id: 'cp1',
    email: 'hr@zicta.zm',
    name: 'Jane Phiri',
    role: 'COMPANY',
    companyId: 'c1',
  },
  {
    id: 'uadmin1',
    email: 'admin@unza.zm',
    name: 'Dr. Chanda Kapambwe',
    role: 'UNIVERSITY_ADMIN',
    universityId: 'u1',
  },
  {
    id: 'uadmin2',
    email: 'admin@cbu.zm',
    name: 'Prof. John Lungu',
    role: 'UNIVERSITY_ADMIN',
    universityId: 'u2',
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'a1',
    internshipId: 'i1',
    studentId: 's1',
    studentName: 'Bwalya Mulenga',
    internshipTitle: 'Cybersecurity Intern',
    companyName: 'ZICTA',
    status: 'PENDING',
    appliedAt: '2026-04-15',
  },
];
